# Generated by Django 5.0.4 on 2024-09-15 13:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walrus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pictest',
            options={'ordering': ['-created'], 'verbose_name': '图片测试', 'verbose_name_plural': '图片测试'},
        ),
        migrations.AddField(
            model_name='pictest',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='创建时间'),
        ),
    ]
