# Generated by Django 5.1.1 on 2024-09-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walrus', '0002_alter_pictest_options_pictest_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalrusFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('content_type', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Walrus文件',
                'verbose_name_plural': 'Walrus文件',
                'ordering': ['-created'],
            },
        ),
    ]
