# Generated by Django 5.1.1 on 2024-09-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walrus', '0003_walrusfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='walrusfile',
            name='size',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
