# Generated by Django 5.1.1 on 2024-09-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walrus', '0004_walrusfile_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='walrusfile',
            name='remark',
            field=models.CharField(default='', max_length=128, verbose_name='备注'),
        ),
    ]
