# Generated by Django 5.1.1 on 2024-09-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walrus', '0005_walrusfile_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walrusfile',
            name='content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='walrusfile',
            name='created',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='walrusfile',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='walrusfile',
            name='size',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
    ]
